server:
  host: '0.0.0.0'
  shutdownTimeout: '5s'

elasticsearch:
  hosts: ['http://anhtuan-info-elasticsearch:9200']
  username: 'kibana_system'
  password: 'anhtuan'

monitoring.ui.container.elasticsearch.enabled: true